name: Test Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: factorioVersion
        uses: DedlySpyder/factorio-version-check@main
      - name: Print experimental version
        run: echo "${{ steps.version.outputs.experimental }}"
      - name: Print stable version
        run: echo "${{ steps.version.outputs.stable }}"
