name: Test Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: version
        name: Get Factorio version
        uses: ./.github/actions/factorio-version
        with:
          version_type: demo
      - name: Print experimental version
        run: echo "${{ steps.version.outputs.experimental }}"
      - name: Print stable version
        run: echo "${{ steps.version.outputs.stable }}"
