name: Test tag actions
on:
  release:
    type: released
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "$(( GITHUB_REF ))"
#      - run: ./.github/workflows/scripts/promote_tag.sh
#        shell: bash
